export const universities = [
    { value: 'University of Alabama', label: 'University of Alabama' },
    { value: 'Auburn University', label: 'Auburn University' },
    { value: 'University of Alaska Anchorage', label: 'University of Alaska Anchorage' },
    { value: 'University of Alaska Fairbanks', label: 'University of Alaska Fairbanks' },
    { value: 'Arizona State University', label: 'Arizona State University' },
    { value: 'Northern Arizona University', label: 'Northern Arizona University' },
    { value: 'University of Arizona', label: 'University of Arizona' },
    { value: 'University of Arkansas', label: 'University of Arkansas' },
    { value: 'Arkansas State University', label: 'Arkansas State University' },
    { value: 'University of California, Los Angeles (UCLA)', label: 'University of California, Los Angeles (UCLA)' },
    { value: 'University of California, Berkeley (UC Berkeley)', label: 'University of California, Berkeley (UC Berkeley)' },
    { value: 'California State University, Fullerton', label: 'California State University, Fullerton' },
    { value: 'California State University, Northridge', label: 'California State University, Northridge' },
    { value: 'San Jose State University', label: 'San Jose State University' },
    { value: 'University of California, Davis', label: 'University of California, Davis' },
    { value: 'USC', label: 'USC' },
    { value: 'California Polytechnic State University', label: 'California Polytechnic State University' },
    { value: 'University of Colorado Boulder', label: 'University of Colorado Boulder' },
    { value: 'Colorado State University', label: 'Colorado State University' },
    { value: 'University of Colorado Denver', label: 'University of Colorado Denver' },
    { value: 'University of Connecticut', label: 'University of Connecticut' },
    { value: 'University of Delaware', label: 'University of Delaware' },
    { value: 'University of Central Florida', label: 'University of Central Florida' },
    { value: 'Florida International University', label: 'Florida International University' },
    { value: 'University of Florida', label: 'University of Florida' },
    { value: 'Florida State University', label: 'Florida State University' },
    { value: 'University of South Florida', label: 'University of South Florida' },
    { value: 'University of Georgia', label: 'University of Georgia' },
    { value: 'Kennesaw State University', label: 'Kennesaw State University' },
    { value: 'Georgia State University', label: 'Georgia State University' },
    { value: 'University of Hawaii at Manoa', label: 'University of Hawaii at Manoa' },
    { value: 'Boise State University', label: 'Boise State University' },
    { value: 'University of Idaho', label: 'University of Idaho' },
    { value: 'University of Illinois at Urbana-Champaign', label: 'University of Illinois at Urbana-Champaign' },
    { value: 'University of Illinois at Chicago', label: 'University of Illinois at Chicago' },
    { value: 'Northern Illinois University', label: 'Northern Illinois University' },
    { value: 'Eastern Illinois University', label: 'Eastern Illinois University' },
    { value: 'Loyola University Chicago', label: 'Loyola University Chicago' },
    { value: 'Indiana University Bloomington', label: 'Indiana University Bloomington' },
    { value: 'Purdue University', label: 'Purdue University' },
    { value: 'Iowa State University', label: 'Iowa State University' },
    { value: 'University of Iowa', label: 'University of Iowa' },
    { value: 'University of Louisville', label: 'University of Louisville' },
    { value: 'Western Kentucky University', label: 'Western Kentucky University' },
    { value: 'University of Kentucky', label: 'University of Kentucky' },
    { value: 'Louisiana State University', label: 'Louisiana State University' },
    { value: 'University of Maryland, College Park', label: 'University of Maryland, College Park' },
    { value: 'University of Massachusetts Amherst', label: 'University of Massachusetts Amherst' },
    { value: 'Bridgewater State University', label: 'Bridgewater State University' },
    { value: 'University of Michigan, Ann Arbor', label: 'University of Michigan, Ann Arbor' },
    { value: 'Michigan State University', label: 'Michigan State University' },
    { value: 'Eastern Michigan University', label: 'Eastern Michigan University' },
    { value: 'Western Michigan University', label: 'Western Michigan University' },
    { value: 'Wayne State University', label: 'Wayne State University' },
    { value: 'Grand Valley State University', label: 'Grand Valley State University' },
    { value: 'Michigan Tech', label: 'Michigan Tech' },
    { value: 'Central Michigan University', label: 'Central Michigan University' },
    { value: 'Northern Michigan University', label: 'Northern Michigan University' },
    { value: 'Ferris State University', label: 'Ferris State University' },
    { value: 'University of Minnesota Twin Cities', label: 'University of Minnesota Twin Cities' },
    { value: 'University of Mississippi (Ole Miss)', label: 'University of Mississippi (Ole Miss)' },
    { value: 'Mississippi State University', label: 'Mississippi State University' },
    { value: 'University of Missouri', label: 'University of Missouri' },
    { value: 'University of Nebraska-Lincoln', label: 'University of Nebraska-Lincoln' },
    { value: 'University of Nevada, Reno (UNR)', label: 'University of Nevada, Reno (UNR)' },
    { value: 'Nevada State University', label: 'Nevada State University' },
    { value: 'Rutgers University-New Brunswick', label: 'Rutgers University-New Brunswick' },
    { value: 'Rutgers University-Newark', label: 'Rutgers University-Newark' },
    { value: 'New Jersey Institute of Technology (NJIT)', label: 'New Jersey Institute of Technology (NJIT)' },
    { value: 'Rowan University', label: 'Rowan University' },
    { value: 'State University of New York- Buffalo (SUNY)', label: 'State University of New York- Buffalo (SUNY)' },
    { value: 'Stony Brook University', label: 'Stony Brook University' },
    { value: 'Hunter College', label: 'Hunter College' },
    { value: 'University of North Carolina at Chapel Hill', label: 'University of North Carolina at Chapel Hill' },
    { value: 'North Carolina State University', label: 'North Carolina State University' },
    { value: 'North Dakota State University', label: 'North Dakota State University' },
    { value: 'University of North Dakota', label: 'University of North Dakota' },
    { value: 'Ohio State University', label: 'Ohio State University' },
    { value: 'University of Cincinnati', label: 'University of Cincinnati' },
    { value: 'Kent State University', label: 'Kent State University' },
    { value: 'Ohio University', label: 'Ohio University' },
    { value: 'University of Oklahoma', label: 'University of Oklahoma' },
    { value: 'University of Central Oklahoma', label: 'University of Central Oklahoma' },
    { value: 'Oklahoma State University', label: 'Oklahoma State University' },
    { value: 'Oregon State University', label: 'Oregon State University' },
    { value: 'University of Oregon', label: 'University of Oregon' },
    { value: 'Pennsylvania State University-Harrisburg', label: 'Pennsylvania State University-Harrisburg' },
    { value: 'University of Pittsburgh', label: 'University of Pittsburgh' },
    { value: 'University of Rhode Island', label: 'University of Rhode Island' },
    { value: 'University of South Carolina', label: 'University of South Carolina' },
    { value: 'Clemson University', label: 'Clemson University' },
    { value: 'College of Charleston', label: 'College of Charleston' },
    { value: 'University of South Dakota', label: 'University of South Dakota' },
    { value: 'South Dakota State University', label: 'South Dakota State University' },
    { value: 'University of Tennessee, Knoxville', label: 'University of Tennessee, Knoxville' },
    { value: 'University of Texas at Dallas', label: 'University of Texas at Dallas' },
    { value: 'University of Texas at Austin', label: 'University of Texas at Austin' },
    { value: 'Texas A&M University', label: 'Texas A&M University' },
    { value: 'University of Houston', label: 'University of Houston' },
    { value: 'University of North Texas', label: 'University of North Texas' },
    { value: 'University of Texas at Arlington', label: 'University of Texas at Arlington' },
    { value: 'Texas State University', label: 'Texas State University' },
    { value: 'Virginia Polytechnic Institute and State University', label: 'Virginia Polytechnic Institute and State University' },
    { value: 'University of Washington', label: 'University of Washington' },
    { value: 'Washington State University', label: 'Washington State University' },
    { value: 'West Virginia University', label: 'West Virginia University' },
    { value: 'Marshall University', label: 'Marshall University' },
    { value: 'University of Wisconsin-Madison', label: 'University of Wisconsin-Madison' },
    // Add more universities as needed
  ];
  